package com.example.superdupergame.pacman.models;

import java.util.Queue;

public class NeumontMaze extends Maze
{
    //public static final int ROWS = 17;
    //public static final int COLS = 68;
    public static final int HOME_ROW = 12;
    public static final int HOME_COL = 12;

    public static final int TILE_SIZE = 35;


    public NeumontMaze()
    {
        super(17, 68, 335);
        initializeMaze();
    }

    @Override
    protected void initializeMaze()
    {
        grid = new Tile[][]{
            /*0*/ {Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W},
            /*1*/ {Tile.W, Tile.R, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P ,Tile.R, Tile.W},
            /*2*/ {Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W},
            /*3*/ {Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W},
            /*4*/ {Tile.W, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.E, Tile.E, Tile.E, Tile.E, Tile.E, Tile.E, Tile.E, Tile.E, Tile.E, Tile.E, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.W},
            /*5*/ {Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.R, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.E, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.E, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W},
            /*6*/ {Tile.E, Tile.E, Tile.E, Tile.E, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.E, Tile.W, Tile.E, Tile.E, Tile.E, Tile.E, Tile.E, Tile.E, Tile.W, Tile.E, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.E, Tile.E, Tile.E, Tile.E},
            /*7*/ {Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.E, Tile.W, Tile.E, Tile.E, Tile.E, Tile.E, Tile.E, Tile.E, Tile.W, Tile.E, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.R, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W},
          /*(8)*/ {Tile.E, Tile.E, Tile.E, Tile.E, Tile.E, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.E, Tile.W, Tile.E, Tile.E, Tile.E, Tile.E, Tile.E, Tile.E, Tile.W, Tile.E, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.E, Tile.E, Tile.E, Tile.E, Tile.E},
            /*9*/ {Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.P, Tile.P, Tile.E, Tile.E, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.E, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W},
           /*10*/ {Tile.E, Tile.E, Tile.E, Tile.E, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.E, Tile.E, Tile.E, Tile.E, Tile.E, Tile.E, Tile.E, Tile.E, Tile.E, Tile.E, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.E, Tile.E, Tile.E, Tile.E},
           /*11*/ {Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W},
           /*12*/ {Tile.W, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P ,Tile.P, Tile.W},
           /*13*/ {Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.P, Tile.P, Tile.P, Tile.W, Tile.W, Tile.P, Tile.P, Tile.P, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W},
           /*14*/ {Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.P, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.P, Tile.W},
           /*15*/ {Tile.W, Tile.R, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.W, Tile.W, Tile.P, Tile.E, Tile.E, Tile.P, Tile.W, Tile.W, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.W, Tile.W, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.W, Tile.W, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.P, Tile.R, Tile.W},
           /*16*/ {Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W, Tile.W}
        };
    }

}
